Repository DSCI-310/DSCI-310-Group-5, pull requests merged in 2022-04, with the labels that each got.

#41 modified dockerfile, edit README docker instruction
  README.md
Labels: documentation, code base, bug fixes

#44 Added in text References
  doc/jbook/breast_cancer_prediction.md
  doc/jbook/references.bib
Labels: documentation, bug fixes

#47 New func - tuned_para_table
  notebooks/breast_cancer_prediction.ipynb
  src/build_test_model.py
  src/plot_confusion_matrix.py
  src/tuned_para_table.py
  tests/test_plot_confusion_matrix.py
  tests/test_tuned_para_table.py
Labels: help wanted

#52 added cittation for code inside function body and references.bib
  doc/jbook/references.bib
  src/mean_cross_val_scores.py
Labels: documentation, code base

#55 modified scripts to import and use the functions from our package
  notebooks/breast_cancer_prediction.ipynb
  src/EDA_plots.py
  src/build_test_model.py
Labels: code base, bug fixes
