Repository DSCI-310/DSCI-310-Group-5, pull requests merged in 2022-02, with the labels that each got.

#10 Modifed codes, commentaries, Dockerfile
  Dockerfile
  analysis.ipynb
Labels: documentation, code base

#15 EDA and plots elaboration
  analysis.ipynb
Labels: code base

#16 gammar/vocab check + summary fixed
  README.md
Labels: documentation
